export const projects = [
    {
      id: 1,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "https://www.github.com",
    },
    {
      id: 2,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "https://www.github.com",
    },
    {
      id: 3,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "https://www.github.com",
    },
    {
      id: 4,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "https://www.github.com",
    },
    {
      id: 5,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "https://www.github.com",
    },
    {
      id: 6,
      img: "https://res.cloudinary.com/dn7qsxzdf/image/upload/v1654297225/portfolio%20daniel/web_negra_trfagx.jpg",
      title: "Lorem ipsum is simply dummy",
      subtitle: "Lorem ipsum",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam quis quod officia molestias voluptate provident ex veniam atque eligendi tempora, ullam aperiam corporis? Asperiores doloremque molestiae ipsum sed eligendi inventore.",
      link: "https://www.example.com",
      github: "",
      disabled: true,
    },
  ];
  